# Generated by Django 6.0.8 on 2026-09-01 01:13

import sysreptor.utils.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackupRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=sysreptor.utils.models.now, editable=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('started', models.DateTimeField(auto_now_add=True)),
                ('completed', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='running', max_length=10)),
                ('trigger', models.CharField(choices=[('manual', 'Manual'), ('daily', 'Daily automatic')], default='manual', max_length=10)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('destination_results', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-started'],
            },
        ),
    ]
